name: Export Tokens

on:
  push:
    paths:
      - 'packages/ui/tailwind.config.ts'

jobs:
  tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm run tokens -F @rfwebapp/ui
      - uses: actions/upload-artifact@v3
        with:
          name: design-tokens
          path: packages/ui/tokens.json
          if-no-files-found: error
